### ISSUE TITLE
Vocabulary question

### ISSUE THREAD

**Issue by madgen** [Microsoft/machine-learning-for-programming-samples#2]
Okay, so due to #1, I can't actually proceed, but I'm gonna ask away something related to Step 2 anyway.

I'm assuming `data_files` is a list of full paths.

Problem 1: Step 2 says use [`Vocabulary.create_vocabulary`](https://github.com/Microsoft/dpu-utils/blob/6622d89e1b2b8e765542c885648678291cde8cda/dpu_utils/mlutils/vocabulary.py#L96) but it's documentation says it only accepts an Iterable (or some other type we don't care about.). Are we supposed to merge Iterables' corresponding to each data file somehow and pass it to create_vocabulary, or maybe use [`Vocabulary.add_or_get_id`](https://github.com/Microsoft/dpu-utils/blob/6622d89e1b2b8e765542c885648678291cde8cda/dpu_utils/mlutils/vocabulary.py#L31) to update for each Iterable (presumably that would defeat the purpose of using an Iterable). As you can see, I'm Python-naïve.

Problem 2: [`Vocabulary.create_vocabulary`](https://github.com/Microsoft/dpu-utils/blob/6622d89e1b2b8e765542c885648678291cde8cda/dpu_utils/mlutils/vocabulary.py#L96) also takes an obligatory `max_size`, what is that supposed to be?

**Comment by madgen** [comment]
Okay, so answer to Problem 2 is that it is the hyperparameter for vocabulary size, right?

**Comment by mmjb** [comment]
Re 1: All of your solutions work; the easiest is to use `itertools.chain` to combine all of the token sequences.

Re 2: Exactly. Any idea how to make that more discoverable?

**Comment by madgen** [comment]
I'll edit the README and do a PR in a sec.
